dist: trusty

services:
  - mysql

language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

before_script:
  - mysql -e 'create database mysql_online_migrations;'

gemfile:
  - gemfiles/rails4_2.gemfile

script: bundle exec rspec spec
