language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

before_script:
  - mysql -e 'create database mysql_online_migrations;'

gemfile:
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile

script: bundle exec rspec spec
