dist: trusty

services:
  - mysql

language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
  - gemfiles/rails6_0.gemfile

jobs:
  exclude:
    - rvm: 2.5
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails5_1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails5_2.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails6_0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails6_0.gemfile

before_script:
  - mysql -e 'create database mysql_online_migrations;'

script: bundle exec rspec spec
