# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
# require 'active_record'
require 'rubygems'
require 'bundler/setup'
require 'mysql_online_migrations'
require 'logger'
#require 'rails'
require 'pry'
require 'support/helpers'
require 'support/shared_examples/mysql_online_migrations'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.include Helpers

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before(:all) do
    setup
    require 'support/rails'
  end

  config.after(:all) do
    teardown
  end

  config.before(:each) do
    stub_execute
    set_ar_setting(true)
  end
end
